version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379" # Проброс порта Redis
    volumes:
      - redis-data:/data # Сохранение данных на хосте
    restart: unless-stopped
    command: [ "redis-server", "--appendonly", "yes" ] # Включение режима сохранения данных на диск

volumes:
  redis-data:
    driver: local
